version: '2'
services:
    new-app:
        image: new
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=new-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    new-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: new-cassandra
    new-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=new-cassandra
    new-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: new-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
